{
  "timestamp": "20250831_103349",
  "dockerfile_path": "envgym/envgym.dockerfile",
  "image_name": "envgym_test_1756636428",
  "build": {
    "success": false,
    "stdout": "",
    "stderr": "#0 building with \"default\" instance using docker driver\n\n#1 [internal] load build definition from envgym.dockerfile\n#1 transferring dockerfile: 1.36kB done\n#1 DONE 0.0s\n\n#2 resolve image config for docker-image://docker.io/docker/dockerfile:1.4\n#2 DONE 0.2s\n\n#3 docker-image://docker.io/docker/dockerfile:1.4@sha256:9ba7531bd80fb0a858632727cf7a112fbfd19b17e94c4e84ced81e24ef1a0dbc\n#3 CACHED\n\n#4 [internal] load .dockerignore\n#4 transferring context: 2B done\n#4 DONE 0.0s\n\n#5 [internal] load metadata for docker.io/continuumio/miniconda3:4.7.12\n#5 DONE 0.1s\n\n#6 [stage-0  1/11] FROM docker.io/continuumio/miniconda3:4.7.12@sha256:6c979670684d970f8ba934bf9b7bf42e77c30a22eb96af1f30a039b484719159\n#6 DONE 0.0s\n\n#7 [internal] load build context\n#7 transferring context: 311B done\n#7 DONE 0.0s\n\n#8 [stage-0  2/11] WORKDIR /app\n#8 CACHED\n\n#9 [stage-0  5/11] RUN mkdir -p plots models results\n#9 CACHED\n\n#10 [stage-0  4/11] RUN --mount=type=cache,target=/var/cache/apt     apt-get update &&     apt-get install -y wget unzip &&     rm -rf /var/lib/apt/lists/*\n#10 CACHED\n\n#11 [stage-0  3/11] RUN echo \"deb http://archive.debian.org/debian buster main\" > /etc/apt/sources.list     && echo \"deb http://archive.debian.org/debian-security buster/updates main\" >> /etc/apt/sources.list\n#11 CACHED\n\n#12 [stage-0  7/11] COPY requirements.txt .\n#12 CACHED\n\n#13 [stage-0  6/11] RUN conda create -y -n ssense python=3.7 &&     echo \"conda activate ssense\" >> ~/.bashrc\n#13 CACHED\n\n#14 [stage-0  8/11] RUN --mount=type=cache,target=/root/.cache/pip     pip install -r requirements.txt\n#14 CACHED\n\n#15 [stage-0  9/11] RUN wget -O dataset.zip \"https://zenodo.org/records/6388301/files/sixthsense-dataset-v2.0.zip\" &&     unzip dataset.zip -d csvs/ &&     rm dataset.zip\n#15 0.217 --2025-08-31 10:33:48--  https://zenodo.org/records/6388301/files/sixthsense-dataset-v2.0.zip\n#15 0.226 Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.43.25, 188.185.48.194, ...\n#15 0.253 Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.\n#15 0.575 HTTP request sent, awaiting response... 404 NOT FOUND\n#15 0.802 2025-08-31 10:33:49 ERROR 404: NOT FOUND.\n#15 0.802 \n#15 ERROR: process \"/bin/sh -c wget -O dataset.zip \\\"https://zenodo.org/records/6388301/files/sixthsense-dataset-v2.0.zip\\\" &&     unzip dataset.zip -d csvs/ &&     rm dataset.zip\" did not complete successfully: exit code: 8\n------\n > [stage-0  9/11] RUN wget -O dataset.zip \"https://zenodo.org/records/6388301/files/sixthsense-dataset-v2.0.zip\" &&     unzip dataset.zip -d csvs/ &&     rm dataset.zip:\n0.217 --2025-08-31 10:33:48--  https://zenodo.org/records/6388301/files/sixthsense-dataset-v2.0.zip\n0.226 Resolving zenodo.org (zenodo.org)... 188.185.45.92, 188.185.43.25, 188.185.48.194, ...\n0.253 Connecting to zenodo.org (zenodo.org)|188.185.45.92|:443... connected.\n404 NOT FOUND\n0.802 2025-08-31 10:33:49 ERROR 404: NOT FOUND.\n0.802 \n------\nERROR: failed to solve: process \"/bin/sh -c wget -O dataset.zip \\\"https://zenodo.org/records/6388301/files/sixthsense-dataset-v2.0.zip\\\" &&     unzip dataset.zip -d csvs/ &&     rm dataset.zip\" did not complete successfully: exit code: 8\n"
  },
  "run": {
    "success": false,
    "stdout": "",
    "stderr": ""
  }
}