{
  "timestamp": "20250830_014734",
  "dockerfile_path": "envgym/envgym.dockerfile",
  "image_name": "envgym_test_1756518453",
  "build": {
    "success": false,
    "stdout": "",
    "stderr": "#0 building with \"default\" instance using docker driver\n\n#1 [internal] load build definition from envgym.dockerfile\n#1 transferring dockerfile: 954B done\n#1 DONE 0.0s\n\n#2 [internal] load metadata for docker.io/library/ubuntu:22.04\n#2 DONE 0.2s\n\n#3 [internal] load .dockerignore\n#3 transferring context: 2B done\n#3 DONE 0.0s\n\n#4 [ 1/10] FROM docker.io/library/ubuntu:22.04@sha256:1aa979d85661c488ce030ac292876cf6ed04535d3a237e49f61542d8e5de5ae0\n#4 DONE 0.0s\n\n#5 [ 2/10] RUN apt-get update &&     apt-get install -y curl unzip zip git subversion software-properties-common &&     add-apt-repository ppa:deadsnakes/ppa -y &&     apt-get update &&     apt-get install -y python3.11 python3.11-dev python3.11-venv\n#5 CACHED\n\n#6 [ 3/10] RUN curl -s \"https://get.sdkman.io\" | bash &&     chmod a+x \"$HOME/.sdkman/bin/sdkman-init.sh\"\n#6 CACHED\n\n#7 [ 4/10] RUN bash -c \"source $HOME/.sdkman/bin/sdkman-init.sh && sdk install java 23.0.1-graal\"\n#7 CACHED\n\n#8 [ 5/10] RUN bash -c \"source $HOME/.sdkman/bin/sdkman-init.sh && sdk install maven\"\n#8 CACHED\n\n#9 [internal] load build context\n#9 transferring context: 502.59kB 0.0s done\n#9 DONE 0.1s\n\n#10 [ 6/10] RUN bash -c \"source $HOME/.sdkman/bin/sdkman-init.sh && gu install python\"\n#10 0.242 bash: line 1: gu: command not found\n#10 ERROR: process \"/bin/sh -c bash -c \\\"source $HOME/.sdkman/bin/sdkman-init.sh && gu install python\\\"\" did not complete successfully: exit code: 127\n------\n > [ 6/10] RUN bash -c \"source $HOME/.sdkman/bin/sdkman-init.sh && gu install python\":\n0.242 bash: line 1: gu: command not found\n------\nenvgym.dockerfile:21\n--------------------\n  19 |     ENV PATH=\"$GRAALVM_HOME/bin:$MAVEN_HOME/bin:$PATH\"\n  20 |     \n  21 | >>> RUN bash -c \"source $HOME/.sdkman/bin/sdkman-init.sh && gu install python\"\n  22 |     \n  23 |     RUN python3.11 -m pip install pytest\n--------------------\nERROR: failed to solve: process \"/bin/sh -c bash -c \\\"source $HOME/.sdkman/bin/sdkman-init.sh && gu install python\\\"\" did not complete successfully: exit code: 127\n"
  },
  "run": {
    "success": false,
    "stdout": "",
    "stderr": ""
  }
}